typography_spectrum: 0.38454123260453343
color:
  brandColors:
    - '#070105'
    - '#381010'
    - '#53925e'
    - '#4c5d3f'
    - '#85bf8f'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.41858760616742074
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.48731
analytics:
  google: null
  facebook: null
  twitter: null
name: Mensaje del Cielo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Buenas Nuevas
description: '#TeBendigo'
purpose: []
